#!/usr/bin/env python3
"""
generate_nssl_sounding_czml_from_csv.py

Generate animated Cesium CZML from NSSL MW41 CSV sounding files.

This CSV-based version uses the real lat/lon columns, so the radiosonde moves
horizontally with the balloon drift instead of going straight up from one fixed
launch lon/lat.

Expected NSSL CSV layout:
- Row 1: metadata labels
- Row 2: metadata values
- Row 3: data column names
- Row 4+: sounding rows

Examples:

Nov18:
python generate_nssl_sounding_czml_from_csv.py \
  /home/dacharya/fcx-playground-backend/notebooks/tiles/public/sounding/nssl/Nov18/data/NSSL1_MW41_output_20221118_225843.csv \
  --out /home/dacharya/fcx-playground-backend/notebooks/tiles/public/sounding/nssl/Nov18/output \
  --name nssl1_225843 \
  --launch-time 2022-11-18T22:58:43Z

Nov19:
python generate_nssl_sounding_czml_from_csv.py \
  /home/dacharya/fcx-playground-backend/notebooks/tiles/public/sounding/nssl/Nov19/data/NSSL1_MW41_output_20221119_013925.csv \
  --out /home/dacharya/fcx-playground-backend/notebooks/tiles/public/sounding/nssl/Nov19/output \
  --name nssl1_013925 \
  --launch-time 2022-11-19T01:39:25Z
"""

import argparse
import json
import math
import re
from pathlib import Path

import pandas as pd


def safe_slug(value):
    value = str(value).strip()
    value = re.sub(r"[^A-Za-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value)
    return value.strip("_").lower() or "sounding"


def default_name_from_input(input_path):
    name = Path(input_path).stem
    name = name.replace("NSSL1_MW41_output_", "")
    return safe_slug(name)


def resolve_output_path(out_arg, name, input_path):
    out = Path(out_arg)

    if out.suffix.lower() == ".czml":
        out.parent.mkdir(parents=True, exist_ok=True)
        return out

    final_name = safe_slug(name) if name else default_name_from_input(input_path)
    out.mkdir(parents=True, exist_ok=True)
    return out / f"{final_name}_sounding_animated.czml"


def parse_timestamp(value):
    if value is None:
        return pd.NaT

    text = str(value).strip()

    if not text:
        return pd.NaT

    # CSV Date-Time often looks like [2022-11-18T23:01:54.0297419]
    text = text.strip("[]")

    ts = pd.to_datetime(text, errors="coerce", utc=True)

    return ts


def iso_z(ts):
    ts = pd.Timestamp(ts)
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    else:
        ts = ts.tz_convert("UTC")
    return ts.isoformat().replace("+00:00", "Z")


def numeric_series(df, col):
    if col not in df.columns:
        return pd.Series([pd.NA] * len(df))
    return pd.to_numeric(df[col], errors="coerce")


def read_nssl_csv(input_path, position_source="filtered"):
    """
    Reads NSSL CSV with header row at line 3.

    position_source:
      filtered -> Filtered Latitude, Filtered Longitude, Filtered Altitude (m)
      gps      -> GPS Latitude, GPS Longitude, GPS Altitude (m)
    """
    df = pd.read_csv(input_path, header=2)

    # Drop fully empty trailing columns generated by extra commas.
    df = df.dropna(axis=1, how="all")
    df.columns = [str(c).strip() for c in df.columns]

    if position_source == "gps":
        lat_col = "GPS Latitude"
        lon_col = "GPS Longitude"
        alt_col = "GPS Altitude (m)"
    else:
        lat_col = "Filtered Latitude"
        lon_col = "Filtered Longitude"
        alt_col = "Filtered Altitude (m)"

    required = [lat_col, lon_col, alt_col]
    missing = [c for c in required if c not in df.columns]

    if missing:
        raise RuntimeError(
            f"Missing required position columns for source '{position_source}': {missing}\n"
            f"Available columns: {list(df.columns)}"
        )

    out = pd.DataFrame()
    out["lat"] = numeric_series(df, lat_col)
    out["lon"] = numeric_series(df, lon_col)
    out["alt_m"] = numeric_series(df, alt_col)

    # Filtered PTU fields.
    out["temp_c"] = numeric_series(df, "Filtered Temperature (K)") - 273.15
    out["dewpoint_c"] = numeric_series(df, "Filtered Dewpoint (K)") - 273.15
    out["rh"] = numeric_series(df, "Filtered Humidity")
    out["pressure_hpa"] = numeric_series(df, "Filtered Pressure (mb)")
    out["wind_dir_deg"] = numeric_series(df, "Filtered Wind Dir")

    # Filtered Wind Spd is m/s in CSV. Convert to knots for UI consistency.
    wind_ms = numeric_series(df, "Filtered Wind Spd (m/s)")
    out["wind_ms"] = wind_ms
    out["wind_kt"] = wind_ms * 1.943844

    out["mixr"] = numeric_series(df, "Calculated Mixing Ratio")

    # Add optional raw/GPS fields for description.
    out["gps_lat"] = numeric_series(df, "GPS Latitude")
    out["gps_lon"] = numeric_series(df, "GPS Longitude")
    out["gps_alt_m"] = numeric_series(df, "GPS Altitude (m)")
    out["raw_temp_c"] = numeric_series(df, "RawPTU Temperature") - 273.15
    out["raw_pressure_hpa"] = numeric_series(df, "RawPTU Pressure")

    # Time: prefer GPS Time Record, fallback Date-Time, fallback later.
    if "GPS Time Record" in df.columns:
        parsed = df["GPS Time Record"].apply(parse_timestamp)
    elif "Date-Time" in df.columns:
        parsed = df["Date-Time"].apply(parse_timestamp)
    else:
        parsed = pd.Series([pd.NaT] * len(df))

    out["time"] = parsed

    # Clean rows.
    out = out.replace([float("inf"), float("-inf")], pd.NA)
    out = out.dropna(subset=["lat", "lon", "alt_m"])
    out = out[
        out["lat"].between(-90, 90)
        & out["lon"].between(-180, 180)
        & out["alt_m"].between(-500, 40000)
    ].copy()

    out = out.reset_index(drop=True)

    if out.empty:
        raise RuntimeError(f"No valid CSV sounding rows after cleaning: {input_path}")

    return out


def apply_times(df, launch_time, seconds_per_row=1.0):
    df = df.copy()

    good_time = df["time"].notna()

    if good_time.any():
        # Use parsed UTC time from CSV where available.
        first_valid = df.loc[good_time, "time"].iloc[0]
        df["time"] = df["time"].ffill().bfill()
        df["elapsed_s"] = (df["time"] - first_valid).dt.total_seconds()
        return df

    # Fallback to launch-time + row index.
    launch_ts = pd.Timestamp(launch_time)
    if launch_ts.tzinfo is None:
        launch_ts = launch_ts.tz_localize("UTC")
    else:
        launch_ts = launch_ts.tz_convert("UTC")

    df["elapsed_s"] = df.index.astype(float) * float(seconds_per_row)
    df["time"] = df["elapsed_s"].apply(lambda s: launch_ts + pd.Timedelta(seconds=float(s)))

    return df


def temp_color(t):
    if not math.isfinite(t):
        return [180, 180, 180, 200]
    if t <= -20:
        return [80, 80, 255, 230]
    if t <= -10:
        return [0, 180, 255, 230]
    if t <= 0:
        return [0, 255, 180, 230]
    if t <= 10:
        return [255, 220, 0, 230]
    return [255, 80, 0, 230]


def wind_arrow(drct):
    if not math.isfinite(drct):
        return "•"
    arrows = ["↑", "↗", "→", "↘", "↓", "↙", "←", "↖"]
    idx = int(((float(drct) + 22.5) % 360) // 45)
    return arrows[idx]


def fmt(value, digits=1, suffix=""):
    try:
        value = float(value)
        if not math.isfinite(value):
            return ""
        return f"{value:.{digits}f}{suffix}"
    except Exception:
        return ""


def build_description(row, t0, position_source):
    return f"""
    <table style="border-collapse:collapse;">
      <tr><td><b>Time</b></td><td>{iso_z(t0)}</td></tr>
      <tr><td><b>Position Source</b></td><td>{position_source}</td></tr>
      <tr><td><b>Latitude</b></td><td>{fmt(row["lat"], 5)}</td></tr>
      <tr><td><b>Longitude</b></td><td>{fmt(row["lon"], 5)}</td></tr>
      <tr><td><b>Height</b></td><td>{fmt(row["alt_m"], 1, " m")}</td></tr>
      <tr><td><b>Pressure</b></td><td>{fmt(row["pressure_hpa"], 1, " hPa")}</td></tr>
      <tr><td><b>Temperature</b></td><td>{fmt(row["temp_c"], 1, " °C")}</td></tr>
      <tr><td><b>Dewpoint</b></td><td>{fmt(row["dewpoint_c"], 1, " °C")}</td></tr>
      <tr><td><b>RH</b></td><td>{fmt(row["rh"], 0, " %")}</td></tr>
      <tr><td><b>Wind</b></td><td>{fmt(row["wind_dir_deg"], 0, "°")} / {fmt(row["wind_ms"], 1, " m/s")} ({fmt(row["wind_kt"], 0, " kt")})</td></tr>
      <tr><td><b>Mixing Ratio</b></td><td>{fmt(row["mixr"], 2, " g/kg")}</td></tr>
      <tr><td><b>GPS Lat/Lon</b></td><td>{fmt(row["gps_lat"], 5)}, {fmt(row["gps_lon"], 5)}</td></tr>
      <tr><td><b>GPS Alt</b></td><td>{fmt(row["gps_alt_m"], 1, " m")}</td></tr>
    </table>
    """


def make_positions_property(df):
    start_time = df["time"].iloc[0]
    first_elapsed = float(df["elapsed_s"].iloc[0])

    positions = []
    for _, r in df.iterrows():
        seconds = float(r["elapsed_s"] - first_elapsed)
        positions += [
            round(seconds, 3),
            float(r["lon"]),
            float(r["lat"]),
            float(r["alt_m"]),
        ]

    return {
        "epoch": iso_z(start_time),
        "cartographicDegrees": positions,
        "interpolationAlgorithm": "LINEAR",
        "interpolationDegree": 1,
    }


def make_static_path_positions(df, max_points=1200):
    positions = []

    step = max(1, math.ceil(len(df) / max_points))
    path_df = df.iloc[::step].copy()
    if len(path_df) > 0 and path_df.index[-1] != df.index[-1]:
        path_df = pd.concat([path_df, df.iloc[[-1]]])

    for _, r in path_df.iterrows():
        positions += [
            float(r["lon"]),
            float(r["lat"]),
            float(r["alt_m"]),
        ]

    return positions


def make_czml(
    df,
    name,
    title,
    sample_every,
    point_every,
    wind_every,
    clock_multiplier,
    position_source,
):
    df = df.iloc[::sample_every].copy().reset_index(drop=True)

    start = df["time"].iloc[0]
    end = df["time"].iloc[-1]
    interval = f"{iso_z(start)}/{iso_z(end)}"

    final_name = safe_slug(name)
    display_title = title or f"{name.upper()} NSSL MW41 Sounding"

    positions_property = make_positions_property(df)
    static_path_positions = make_static_path_positions(df)

    first = df.iloc[0]
    launch_lon = float(first["lon"])
    launch_lat = float(first["lat"])
    launch_alt = float(first["alt_m"])

    czml = [
        {
            "id": "document",
            "name": display_title,
            "version": "1.0",
            "clock": {
                "interval": interval,
                "currentTime": iso_z(start),
                "multiplier": clock_multiplier,
                "range": "LOOP_STOP",
                "step": "SYSTEM_CLOCK_MULTIPLIER",
            },
        },
        {
            "id": f"{final_name}_static_path",
            "name": f"{name} Full Sounding Track",
            "polyline": {
                "positions": {
                    "cartographicDegrees": static_path_positions,
                },
                "width": 4,
                "material": {
                    "polylineGlow": {
                        "color": {"rgba": [255, 255, 255, 210]},
                        "glowPower": 0.18,
                    }
                },
                "clampToGround": False,
            },
            "description": f"<h3>{name} full radiosonde trajectory</h3>",
        },
        {
            "id": f"{final_name}_radiosonde_balloon",
            "name": "Animated Radiosonde Balloon",
            "availability": interval,
            "position": positions_property,
            "point": {
                "pixelSize": 18,
                "color": {"rgba": [255, 255, 0, 255]},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 3,
                "disableDepthTestDistance": 1000000000,
            },
            "label": {
                "text": name,
                "font": "18px sans-serif",
                "fillColor": {"rgba": [255, 255, 255, 255]},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 3,
                "style": "FILL_AND_OUTLINE",
                "pixelOffset": {"cartesian2": [0, -40]},
                "disableDepthTestDistance": 1000000000,
            },
            "path": {
                "show": True,
                "leadTime": 0,
                "trailTime": 100000,
                "width": 4,
                "resolution": 1,
                "material": {
                    "solidColor": {
                        "color": {"rgba": [255, 255, 255, 210]}
                    }
                },
            },
            "description": (
                f"<h3>{name} Animated Radiosonde</h3>"
                f"<p>Uses real lat/lon from CSV position source: <b>{position_source}</b>.</p>"
            ),
        },
        {
            "id": f"{final_name}_launch_site",
            "name": "Sounding Launch Site",
            "position": {
                "cartographicDegrees": [launch_lon, launch_lat, launch_alt]
            },
            "point": {
                "pixelSize": 16,
                "color": {"rgba": [255, 180, 0, 255]},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 2,
                "disableDepthTestDistance": 1000000000,
            },
            "label": {
                "text": "Launch Site",
                "font": "16px sans-serif",
                "fillColor": {"rgba": [255, 255, 255, 255]},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 3,
                "style": "FILL_AND_OUTLINE",
                "pixelOffset": {"cartesian2": [0, -35]},
                "disableDepthTestDistance": 1000000000,
            },
        },
    ]

    # Temperature colored sample points along actual path.
    for idx, r in df.iloc[::point_every].iterrows():
        t0 = r["time"]
        h = float(r["alt_m"])
        temp = float(r["temp_c"]) if pd.notna(r["temp_c"]) else float("nan")

        czml.append({
            "id": f"{final_name}_profile_temp_point_{idx}",
            "name": f"{h:.0f} m | {temp:.1f} °C" if math.isfinite(temp) else f"{h:.0f} m",
            "availability": f"{iso_z(t0)}/{iso_z(end)}",
            "description": build_description(r, t0, position_source),
            "position": {
                "cartographicDegrees": [float(r["lon"]), float(r["lat"]), h]
            },
            "point": {
                "pixelSize": 8,
                "color": {"rgba": temp_color(temp)},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 1,
                "disableDepthTestDistance": 1000000000,
            },
        })

    # Wind labels offset very slightly east from each actual point.
    for idx, r in df.iloc[::wind_every].iterrows():
        t0 = r["time"]
        h = float(r["alt_m"])
        drct = float(r["wind_dir_deg"]) if pd.notna(r["wind_dir_deg"]) else float("nan")
        kt = float(r["wind_kt"]) if pd.notna(r["wind_kt"]) else float("nan")

        text = f"{wind_arrow(drct)} {kt:.0f} kt" if math.isfinite(kt) else wind_arrow(drct)

        czml.append({
            "id": f"{final_name}_wind_arrow_{idx}",
            "name": f"Wind {h:.0f} m",
            "availability": f"{iso_z(t0)}/{iso_z(end)}",
            "position": {
                "cartographicDegrees": [
                    float(r["lon"]) + 0.01,
                    float(r["lat"]),
                    h,
                ]
            },
            "label": {
                "text": text,
                "font": "15px sans-serif",
                "fillColor": {"rgba": [120, 220, 255, 255]},
                "outlineColor": {"rgba": [0, 0, 0, 255]},
                "outlineWidth": 3,
                "style": "FILL_AND_OUTLINE",
                "disableDepthTestDistance": 1000000000,
            },
        })

    return czml, df, start, end


def main():
    parser = argparse.ArgumentParser(
        description="Generate animated Cesium CZML from NSSL MW41 CSV sounding files using real lat/lon."
    )

    parser.add_argument("input", help="Input NSSL MW41 CSV file.")
    parser.add_argument(
        "--out",
        required=True,
        help="Output .czml path or output folder. If folder, writes <name>_sounding_animated.czml.",
    )
    parser.add_argument("--name", default=None, help="Output/entity name prefix.")
    parser.add_argument("--title", default=None, help="CZML document display title.")
    parser.add_argument(
        "--launch-time",
        default=None,
        help="Fallback launch time if CSV time cannot be parsed, e.g. 2022-11-18T22:58:43Z.",
    )
    parser.add_argument(
        "--position-source",
        choices=["filtered", "gps"],
        default="filtered",
        help="Use filtered lat/lon/alt or raw GPS lat/lon/alt. Default: filtered.",
    )
    parser.add_argument("--sample-every", type=int, default=3, help="Downsample rows. Default: 3.")
    parser.add_argument("--point-every", type=int, default=2, help="Temp point every N downsampled rows. Default: 2.")
    parser.add_argument("--wind-every", type=int, default=20, help="Wind label every N downsampled rows. Default: 20.")
    parser.add_argument("--clock-multiplier", type=int, default=30, help="Cesium clock multiplier. Default: 30.")
    parser.add_argument(
        "--seconds-per-row",
        type=float,
        default=1.0,
        help="Fallback time spacing if CSV time cannot be parsed. Default: 1.",
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(input_path)

    name = args.name or default_name_from_input(input_path)
    out_path = resolve_output_path(args.out, name, input_path)

    launch_time = args.launch_time or "1970-01-01T00:00:00Z"

    df_raw = read_nssl_csv(input_path, position_source=args.position_source)
    df_raw = apply_times(df_raw, launch_time=launch_time, seconds_per_row=args.seconds_per_row)

    czml, df_used, start, end = make_czml(
        df=df_raw,
        name=name,
        title=args.title,
        sample_every=args.sample_every,
        point_every=args.point_every,
        wind_every=args.wind_every,
        clock_multiplier=args.clock_multiplier,
        position_source=args.position_source,
    )

    out_path.write_text(json.dumps(czml, indent=2), encoding="utf-8")

    print("Wrote:", out_path)
    print("Input:", input_path)
    print("Position source:", args.position_source)
    print("Rows raw:", len(df_raw))
    print("Rows used:", len(df_used))
    print("Start:", iso_z(start))
    print("End:", iso_z(end))
    print("Latitude range:", float(df_used["lat"].min()), float(df_used["lat"].max()))
    print("Longitude range:", float(df_used["lon"].min()), float(df_used["lon"].max()))
    print("Height range:", float(df_used["alt_m"].min()), float(df_used["alt_m"].max()))


if __name__ == "__main__":
    main()
